name: CI

permissions: {}

on:
  pull_request:
  push:
    branches: ["main"]
  workflow_dispatch:

# Only allow one instance of this workflow for each PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41  # v7.1.2
        with:
          version: "latest"
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3  # v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check formatting and linting
        run: just check

  package:
    name: "Build & verify package"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  #v6.0.2
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41  # v7.1.2
        with:
          version: "latest"
      - name: "Build package"
        run: "uv build"
      - name: "List result"
        run: "ls -l dist"
      - name: "Check wheel contents"
        run: "uvx check-wheel-contents --toplevel classify dist/*.whl"
      - name: "Check long_description"
        run: "uvx twine check dist/*"

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  #v6.0.2
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41  # v7.1.2
        with:
          python-version: ${{ matrix.python-version }}
          version: "latest"
      - uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3  # v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check formatting and linting
        run: uv run -m nox --python ${{ matrix.python-version }}

  zizmor:
    runs-on: ubuntu-latest
    permissions:
      security-events: write  # Required for upload-sarif (used by zizmor-action) to upload SARIF files.
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  #v6.0.2
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: zizmorcore/zizmor-action@6599ee8b7a49aef6a770f63d261d214911a7ce02 # v0.6.0
