name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41  # v7.1.2
        with:
          version: "latest"
      - uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6  # 2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check formatting and linting
        run: just check

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41  # v7.1.2
        with:
          python-version: ${{ matrix.python-version }}
          version: "latest"
      - uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6  # 2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Check formatting and linting
        run: uv run -m nox --python ${{ matrix.python-version }}
